# Generated by Django 4.0.4 on 2022-05-27 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_create_by_category_create_by_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='create_by_id',
        ),
    ]
