# Generated by Django 4.0.4 on 2022-05-25 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_account_options_alter_account_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Only alphanumeric characters are allowed.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator('[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')], verbose_name='username'),
        ),
    ]
